#ifndef DEFINITION_H
#define DEFINITION_H
#define NameProgram "AddClass"
#define ID_Helper "-help"
#define ID_Path "-pc"
#define ID_PathTemplate "-pct"
#define ID_CreativeClass "-c"
#define ID_Set "-rs"
#define ID_Get "-rg"
#define ID_SetGet "-rsg"
#define ID_Main "-m"
#define ID_CreativeClassTemplate "-ct"
#define nameMain "main"
#define iostream "<iostream>"
#define Version "V 0.1"
#define T_int "int"
#define T_float "float"
#define T_double "double"
#define T_char "char"
#define T_bool "bool"
#define T_void "void"
#define T_un "undefinded"
#endif //! DEFINITION_H